# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170104_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
