# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 10:33
from __future__ import unicode_literals

from django.db import migrations
import editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_archive_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=editor.models.EditorField(),
        ),
    ]
